export type CliHelpTopic = "root" | "project";

export function rootHelpText(): string {
  return [
    "PatchRelay",
    "",
    "patchrelay is a local service and CLI that connects Linear issue delegation to Codex worktrees on your machine.",
    "",
    "Usage:",
    "  patchrelay <command> [args] [flags]",
    "  patchrelay <issueKey>                 # shorthand for `patchrelay inspect <issueKey>`",
    "",
    "First-time setup:",
    "  1. patchrelay init <public-https-url>",
    "  2. Fill in ~/.config/patchrelay/service.env",
    "  3. patchrelay project apply <id> <repo-path>",
    "  4. Add IMPLEMENTATION_WORKFLOW.md and REVIEW_WORKFLOW.md to the repo",
    "  5. patchrelay doctor",
    "",
    "Why init needs the public URL:",
    "  Linear must reach PatchRelay at a public HTTPS origin for both the webhook endpoint",
    "  and the OAuth callback. `patchrelay init` writes that origin to `server.public_base_url`.",
    "",
    "Default behavior:",
    "  PatchRelay already defaults the local bind address, database path, log path, worktree",
    "  root, and Codex runner settings. In the normal",
    "  case you only need the public URL, the required secrets, and at least one project.",
    "  `patchrelay init` installs the system service and config watcher, and `project apply`",
    "  upserts the repo config and reuses or starts the Linear connection flow.",
    "",
    "Commands:",
    "  version [--json]                                        Show the installed PatchRelay build version",
    "  init <public-base-url> [--force] [--json]               Bootstrap the machine-level PatchRelay home",
    "  project apply <id> <repo-path> [--issue-prefix <prefixes>] [--team-id <ids>] [--no-connect] [--no-open] [--timeout <seconds>] [--json]",
    "                                                          Upsert one local repository and connect it to Linear when ready",
    "  doctor [--json]                                         Check secrets, paths, git, and codex",
    "  install-service [--force] [--write-only] [--json]      Reinstall the systemd system service and watcher",
    "  restart-service [--json]                               Reload-or-restart the systemd system service",
    "  connect [--project <projectId>] [--no-open] [--timeout <seconds>] [--json]",
    "                                                          Advanced: start or reuse a Linear installation directly",
    "  installations [--json]                                 Show connected Linear installations",
    "  feed [--follow] [--limit <count>] [--issue <issueKey>] [--project <projectId>] [--kind <kind>] [--stage <stage>] [--status <status>] [--workflow <id>] [--json]",
    "                                                          Show a live operator feed from the daemon",
    "  watch [--issue <issueKey>]                              Live TUI dashboard of issues and runs",
    "  serve                                                  Run the local PatchRelay service",
    "  inspect <issueKey>                                     Show the latest known issue state",
    "  live <issueKey> [--watch] [--json]                     Show the active run status",
    "  report <issueKey> [--run-type <type>] [--run <id>] [--json]",
    "                                                          Show finished run reports",
    "  events <issueKey> [--run <id>] [--method <name>] [--follow] [--json]",
    "                                                          Show raw thread events",
    "  worktree <issueKey> [--cd] [--json]                    Print the issue worktree path",
    "  open <issueKey> [--print] [--json]                     Open Codex in the issue worktree",
    "  retry <issueKey> [--run-type <type>] [--reason <text>] [--json]",
    "                                                          Requeue a run",
    "  list [--active] [--failed] [--project <projectId>] [--json]",
    "                                                          List tracked issues",
    "",
    "Environment options:",
    "  --help, -h              Show help for the root command or current command group",
    "",
    "Automation env vars:",
    "  PATCHRELAY_CONFIG       Override the config file path",
    "  PATCHRELAY_DB_PATH      Override the SQLite database path",
    "  PATCHRELAY_LOG_FILE     Override the log file path",
    "  PATCHRELAY_LOG_LEVEL    Override the log level",
    "",
    "Examples:",
    "  patchrelay init https://patchrelay.example.com",
    "  patchrelay project apply app /absolute/path/to/repo",
    "  patchrelay doctor",
    "  patchrelay USE-54",
    "  patchrelay version --json",
    "",
    "Command help:",
    "  patchrelay help",
    "  patchrelay help project",
    "  patchrelay project --help",
  ].join("\n");
}

export function projectHelpText(): string {
  return [
    "Usage:",
    "  patchrelay project apply <id> <repo-path> [options]",
    "",
    "Commands:",
    "  apply <id> <repo-path>   Create or update a repository entry in the local PatchRelay config",
    "",
    "Options:",
    "  --issue-prefix <prefixes>  Comma-separated issue key prefixes for routing",
    "  --team-id <ids>            Comma-separated Linear team ids for routing",
    "  --no-connect               Save the project without starting or reusing Linear OAuth",
    "  --no-open                  Do not open the browser during connect",
    "  --timeout <seconds>        Override the connect wait timeout",
    "  --json                     Emit structured JSON output",
    "  --help, -h                 Show this help",
    "",
    "Behavior:",
    "  `patchrelay project apply` is the idempotent happy-path command. It updates",
    "  the local config, reruns readiness checks, reloads the service when ready,",
    "  and reuses or starts the Linear connect flow unless `--no-connect` is set.",
    "",
    "Examples:",
    "  patchrelay project apply app /absolute/path/to/repo",
    "  patchrelay project apply app /absolute/path/to/repo --issue-prefix APP",
    "  patchrelay project apply app /absolute/path/to/repo --team-id team-123 --no-connect",
  ].join("\n");
}

export function helpTextFor(topic: CliHelpTopic): string {
  return topic === "project" ? projectHelpText() : rootHelpText();
}
